name: omt
description: "Operation and maintenance tools"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  kayo_package:
    #    git:
    #      url: https://gitee.com/kayoxu/kayo_package.git
    #      ref: 'v3.19'
    path: ../../flutter/plugin/kayo_package
  image_picker: ^1.0.7
  photo_view: ^0.14.0
  syncfusion_flutter_charts: ^24.2.8
  flutter_volume_controller: ^1.3.1
  syncfusion_flutter_pdfviewer: ^24.2.8
  open_filex: ^4.4.0
  share_plus: ^7.2.2
  shared_preferences: ^2.2.2
  package_info_plus: ^5.0.1
  flutter_localization: ^0.2.0
  fluent_ui: ^4.8.6
  system_theme: ^2.3.1
  go_router: ^10.0.0
  file_picker: ^8.0.0+1

  flutter_acrylic: ^1.1.3 #只支持桌面
  window_manager: ^0.3.8 #只支持桌面

  #  dart_vlc_ffi: ^0.2.0+1 #不支持web https://github.com/alexmercerind/dart_vlc?tab=readme-ov-file
  #  dart_vlc: ^0.4.0
  media_kit: ^1.1.10+1  # 全能
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

#dependency_overrides:
#  intl: 0.18.1
#  macos_window_utils: ^1.5.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/login/

  #     fvm flutter build web --web-browser-flag "--disable-web-security"


  #     fvm flutter run -d chrome --web-browser-flag "--disable-web-security"

#  dart pub global activate flutter_cors
#  fluttercors --disable

#    http://192.168.101.189:3000/a.mkv
# https://blog.csdn.net/weixin_43787969/article/details/131086842