name: Build Windows App

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Installer
    runs-on: windows-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置 Flutter 环境 (锁定 3.27.0)
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
          cache: true

      # 3. 安装依赖
      - name: Install Dependencies
        run: flutter pub get

      # 4. 开始编译 (Release 模式)
      - name: Build Windows
        run: flutter build windows --release

      # 5. 生成安装包 (Inno Setup)
      - name: Build Installer
        shell: powershell
        run: |
          choco install innosetup --no-progress
          
          # [必须] 下载中文语言包到 installers 目录
          $LangUrl = "https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/ChineseSimplified.isl"
          Invoke-WebRequest -Uri $LangUrl -OutFile "installers\ChineseSimplified.isl"
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "installers\setup.iss"

      # 6. 上传产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          path: build/windows/installer/*.exe
          retention-days: 3