name: Build Windows App

on:
  push:
    branches: [ "master" ] # 对应你 Jenkins 推送的分支
  workflow_dispatch:      # 允许手动触发

jobs:
  build:
    name: Build Installer
    runs-on: windows-latest

    steps:
      # 1. 拉取代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 配置 Flutter 环境 (已锁定 3.7.12)
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12' # === 关键修改：强制使用 3.7.12 ===
          channel: 'stable'
          cache: true

      # 3. 安装依赖
      - name: Install Dependencies
        run: flutter pub get

      # 4. 开始编译 (Release 模式)
      - name: Build Windows
        run: flutter build windows --release

      # 5. 生成安装包 (Inno Setup)
      # ⚠️ 确保你项目根目录下有 installers/setup.iss 文件
      - name: Create Installer
        uses: Minionguyj/innosetup-script-action@v1.0.0
        with:
          path: installers/setup.iss

      # 6. 上传产物
      # 对应 Jenkins 脚本里的 ARTIFACT_NAME="windows-app"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-app
          # 上传 Inno Setup 生成的 setup.exe
          path: build/windows/installer/*.exe
          retention-days: 3